######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 2 14:25:48 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qtestlib core

include( $$ROOT_DIR/common/qmake/include.pro )

# Input
SOURCES += TestCoreUrl.cpp
